modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="vortex"
version="2.0.0"
displayName="vortex"
displayURL="https://tdjs.link"
credits="DJ"
authors="dj"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.vortex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
